# Model Configuration
model:
  name: "google/vit-base-patch16-224"
  pretrained: true
  num_classes: 6  # ISUP grades 0-5
  img_size: 224
  patch_size: 16
  in_chans: 3
  embed_dim: 768
  depth: 12
  num_heads: 12
  mlp_ratio: 4.0
  qkv_bias: true
  drop_rate: 0.1
  attn_drop_rate: 0.0
  drop_path_rate: 0.1

# Data Configuration
data:
  data_dir: "./../prostate-cancer-grade-assessment"
  train_csv: "train.csv"
  test_csv: "test.csv"
  train_image_dir: "train_images"
  mask_dir: "train_label_masks"
  batch_size: 16
  num_workers: 8
  pin_memory: true
  persistent_workers: true
  patches_per_image: 16  # Number of random patches per image

# Augmentation Configuration
augmentation:
  hflip_prob: 0.5
  vflip_prob: 0.5
  rotation_range: 10
  brightness: 0.1
  contrast: 0.1
  scale_limit: 0.1
  shift_limit: 0.1

# Training Configuration
training:
  epochs: 20
  warmup_epochs: 5
  lr: 5.0e-5
  min_lr: 1.0e-6
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  grad_clip: 1.0
  mixed_precision: true
  accumulate_grad_batches: 1
  val_check_interval: 0.5  # Check validation set twice per epoch

# Logging Configuration
logging:
  log_dir: "./logs"
  experiment_name: "vit_prostate_cancer"
  use_wandb: true
  log_every_n_steps: 50
  save_top_k: 3
  monitor: "val_kappa"
  mode: "max"

# System Configuration
system:
  gpus: 4
  accelerator: "ddp"
  precision: 16 if training.mixed_precision else 32
  deterministic: true
  benchmark: true
  seed: 42
