# TransUNet Configuration for Prostate Cancer Detection

# Model Configuration
model:
  img_size: 224
  patch_size: 16
  num_classes: 6  # ISUP grades 0-5
  embed_dim: 768
  depth: 12
  num_heads: 12
  mlp_ratio: 4
  dropout: 0.1
  seg_classes: 1  # Binary segmentation

# Data Configuration
data:
  data_dir: "./../prostate-cancer-grade-assessment"
  train_csv: "train.csv"
  test_csv: "test.csv"
  train_image_dir: "train_images"
  mask_dir: "train_label_masks"
  batch_size: 128  # Maximized for 32GB GPU
  num_workers: 32  # Increased for better data loading
  pin_memory: true
  persistent_workers: true
  patches_per_image: 20  # More patches for better learning

# Augmentation Configuration
augmentation:
  hflip_prob: 0.5
  vflip_prob: 0.5
  rotation_range: 15
  brightness: 0.15
  contrast: 0.15
  scale_limit: 0.15
  shift_limit: 0.15

# Training Configuration
training:
  epochs: 30  # Increased epochs for better convergence
  warmup_epochs: 5  # Better warmup
  lr: 0.0003  # Higher LR for larger batch size
  min_lr: 0.000001
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  grad_clip: 1.0
  mixed_precision: true
  accumulate_grad_batches: 1

# Logging Configuration
logging:
  log_dir: "./logs"
  checkpoint_dir: "./checkpoints"
  experiment_name: "transunet_prostate_cancer"
  use_wandb: false
  log_every_n_steps: 25  # More frequent logging (was 50)
  save_top_k: 5  # Save more checkpoints (was 3)
  monitor: "val_kappa"
  mode: "max"

# System Configuration
system:
  gpus: 4
  seed: 42
  deterministic: true
  benchmark: true
