# TransUNet Configuration for Prostate Cancer Detection

# Model Configuration
model:
  img_size: 224
  patch_size: 16
  num_classes: 6  # ISUP grades 0-5
  embed_dim: 768
  depth: 12
  num_heads: 12
  mlp_ratio: 4
  dropout: 0.1
  seg_classes: 1  # Binary segmentation

# Data Configuration
data:
  data_dir: "./../prostate-cancer-grade-assessment"
  train_csv: "train.csv"
  test_csv: "test.csv"
  train_image_dir: "train_images"
  mask_dir: "train_label_masks"
  batch_size: 32  # Doubled for better gradient estimates
  num_workers: 4   # Increased workers
  pin_memory: true
  persistent_workers: true
  patches_per_image: 12  # Increased patches per image
  validate_files: true  # Pre-validate files to avoid corrupted images

# Augmentation Configuration - Increased for better learning
augmentation:
  hflip_prob: 0.5  # Increased back to standard
  vflip_prob: 0.5  # Increased back to standard
  rotation_range: 10  # Moderate rotation
  brightness: 0.1  # Increased brightness variation
  contrast: 0.1    # Increased contrast variation
  scale_limit: 0.1 # Increased scale variation
  shift_limit: 0.1 # Increased shift variation

# Training Configuration
training:
  epochs: 15  # Extended for better convergence
  warmup_epochs: 2  # Shorter warmup since we need faster learning
  lr: 0.0001  # 10x increase - still safe but much more effective
  min_lr: 0.00001  # Adjusted proportionally
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  grad_clip: 1.0  # Increased for higher LR
  mixed_precision: false  # Keep disabled for stability
  accumulate_grad_batches: 1

# Logging Configuration
logging:
  log_dir: "./logs"
  checkpoint_dir: "./checkpoints"
  experiment_name: "transunet_prostate_cancer"
  use_wandb: false
  log_every_n_steps: 25
  save_top_k: 3
  monitor: "val_kappa"
  mode: "max"

# System Configuration
system:
  gpus: 1
  seed: 42
  deterministic: true
  benchmark: true
