# TransUNet Configuration for Prostate Cancer Detection

# Model Configuration
model:
  img_size: 224
  patch_size: 16
  num_classes: 6  # ISUP grades 0-5
  embed_dim: 768
  depth: 12
  num_heads: 12
  mlp_ratio: 4
  dropout: 0.1
  seg_classes: 1  # Binary segmentation

# Data Configuration
data:
  data_dir: "./../prostate-cancer-grade-assessment"
  train_csv: "train.csv"
  test_csv: "test.csv"
  train_image_dir: "train_images"
  mask_dir: "train_label_masks"
  batch_size: 16  # VERY small batch for maximum stability
  num_workers: 2   # Minimal workers to prevent issues
  pin_memory: true
  persistent_workers: true
  patches_per_image: 8  # Very conservative patch count
  validate_files: true  # Pre-validate files to avoid corrupted images

# Augmentation Configuration - MINIMAL for stability
augmentation:
  hflip_prob: 0.3  # Reduced probability
  vflip_prob: 0.3  # Reduced probability
  rotation_range: 5  # Much smaller rotation
  brightness: 0.05  # Much smaller brightness change
  contrast: 0.05    # Much smaller contrast change
  scale_limit: 0.05 # Much smaller scale change
  shift_limit: 0.05 # Much smaller shift

# Training Configuration
training:
  epochs: 10
  warmup_epochs: 3  # Longer warmup for stability
  lr: 0.00001  # VERY conservative LR to prevent NaN
  min_lr: 0.000001  # Proportionally adjusted
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  grad_clip: 0.1  # Very aggressive gradient clipping
  mixed_precision: false  # DISABLE mixed precision to prevent NaN
  accumulate_grad_batches: 1

# Logging Configuration
logging:
  log_dir: "./logs"
  checkpoint_dir: "./checkpoints"
  experiment_name: "transunet_prostate_cancer"
  use_wandb: false
  log_every_n_steps: 25
  save_top_k: 3
  monitor: "val_kappa"
  mode: "max"

# System Configuration
system:
  gpus: 1
  seed: 42
  deterministic: true
  benchmark: true
