# TransUNet Configuration for Prostate Cancer Detection

# Model Configuration
model:
  img_size: 224
  patch_size: 16
  num_classes: 6  # ISUP grades 0-5
  embed_dim: 768
  depth: 12
  num_heads: 12
  mlp_ratio: 4
  dropout: 0.1
  seg_classes: 1  # Binary segmentation

# Data Configuration
data:
  data_dir: "./../prostate-cancer-grade-assessment"
  train_csv: "train.csv"
  test_csv: "test.csv"
  train_image_dir: "train_images"
  mask_dir: "train_label_masks"
  batch_size: 128  # Reduced from 80 for stability
  num_workers: 6   # Reduced from 8 to prevent issues
  pin_memory: true
  persistent_workers: true
  patches_per_image: 16  # Reduced from 35 for stability
  validate_files: true  # Pre-validate files to avoid corrupted images

# Augmentation Configuration
augmentation:
  hflip_prob: 0.5
  vflip_prob: 0.5
  rotation_range: 15
  brightness: 0.15
  contrast: 0.15
  scale_limit: 0.15
  shift_limit: 0.15

# Training Configuration
training:
  epochs: 10
  warmup_epochs: 1  # Increased warmup for stability
  lr: 0.0005  # Much lower LR to prevent instability
  min_lr: 0.00001  # Proportionally adjusted
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  grad_clip: 0.5  # Reduced gradient clipping for stability
  mixed_precision: true  # Enable mixed precision to prevent NaN
  accumulate_grad_batches: 1

# Logging Configuration
logging:
  log_dir: "./logs"
  checkpoint_dir: "./checkpoints"
  experiment_name: "transunet_prostate_cancer"
  use_wandb: false
  log_every_n_steps: 25
  save_top_k: 3
  monitor: "val_kappa"
  mode: "max"

# System Configuration
system:
  gpus: 1
  seed: 42
  deterministic: true
  benchmark: true
