# ViTDet + Mask R-CNN Configuration for Prostate Cancer Detection

# Model Configuration
model:
  name: "vitdet_maskrcnn"
  backbone: "ViT-B/16"  # Vision Transformer backbone
  pretrained: true
  num_classes: 6  # ISUP grades 0-5 + background
  img_size: 1024  # Larger images for better detection
  patch_size: 16
  
  # Mask R-CNN specific
  roi_heads:
    num_classes: 6
    batch_size_per_image: 512
    positive_fraction: 0.25
    score_thresh_test: 0.05
    nms_thresh_test: 0.5
    
  # FPN configuration
  fpn:
    in_features: ["res2", "res3", "res4", "res5"]
    out_channels: 256
    
  # RPN configuration
  rpn:
    in_features: ["p2", "p3", "p4", "p5", "p6"]
    pre_nms_topk_train: 2000
    pre_nms_topk_test: 1000
    post_nms_topk_train: 1000
    post_nms_topk_test: 1000
    nms_thresh: 0.7

# Data Configuration
data:
  data_dir: "./../prostate-cancer-grade-assessment"
  train_csv: "train.csv"
  test_csv: "test.csv"
  train_image_dir: "train_images"
  mask_dir: "train_label_masks"
  
  # For object detection
  batch_size: 4  # Smaller batch size for large images
  num_workers: 8
  pin_memory: true
  persistent_workers: true
  
  # Patch extraction
  patch_size: 1024  # Larger patches for detection
  overlap: 128  # Overlap between patches
  min_tumor_area: 1000  # Minimum tumor area in pixels

# Augmentation Configuration
augmentation:
  # Geometric transforms
  hflip_prob: 0.5
  vflip_prob: 0.5
  rotation_range: 90  # Full rotation for histology
  
  # Color transforms (important for histology)
  brightness: 0.2
  contrast: 0.2
  saturation: 0.1
  hue: 0.05
  
  # Advanced augmentations
  elastic_transform_prob: 0.3
  grid_distortion_prob: 0.3
  optical_distortion_prob: 0.3
  
  # Normalization (ImageNet stats)
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# Training Configuration
training:
  epochs: 50
  warmup_epochs: 5
  
  # Learning rates
  base_lr: 0.0001  # Base learning rate
  weight_decay: 0.0001
  momentum: 0.9
  
  # Learning rate schedule
  lr_scheduler: "WarmupMultiStepLR"
  lr_steps: [30, 40]
  lr_gamma: 0.1
  
  # Gradient clipping
  grad_clip: 1.0
  
  # Mixed precision
  mixed_precision: true
  
  # Evaluation
  eval_period: 2000  # Evaluate every N iterations
  checkpoint_period: 5000  # Save checkpoint every N iterations

# Loss Configuration
loss:
  # Classification loss weight
  cls_loss_weight: 1.0
  
  # Box regression loss weight
  bbox_loss_weight: 1.0
  
  # Mask loss weight
  mask_loss_weight: 1.0
  
  # Focal loss for classification (handle class imbalance)
  use_focal_loss: true
  focal_alpha: 0.25
  focal_gamma: 2.0

# Evaluation Configuration
evaluation:
  # Detection metrics
  iou_thresholds: [0.5, 0.75]  # IoU thresholds for mAP
  
  # Classification metrics
  use_cohen_kappa: true
  
  # Visualization
  vis_period: 1000  # Visualize predictions every N iterations
  num_vis_samples: 8

# Logging Configuration
logging:
  log_dir: "./logs_vitdet"
  experiment_name: "vitdet_maskrcnn_prostate"
  use_wandb: true
  wandb_project: "prostate-cancer-vitdet"
  log_every_n_steps: 100
  
  # Model saving
  save_top_k: 3
  monitor: "val_map"
  mode: "max"

# System Configuration
system:
  gpus: 4
  distributed: true  # Use distributed training
  find_unused_parameters: false
  deterministic: true
  seed: 42
